[backend]
host = "127.0.0.1"
port = 8000

[tracker]
max_failed_read = 10
uniques         = 50
debug           = false
path            = ".markers"
size            = 5

[capture]
camera_id = 0
fps       = 60