[backend]
host = "127.0.0.1"
port = 8000

[tracker]
path                  = ".markers"
debug                 = false
failed_read_threshold = 10
uniques               = 50
size                  = 5

[renderer]
fps = 60